### ISSUE TITLE
演示地址进去直接是tomcat admin 页面

### ISSUE THREAD

**Issue by weichengpei** [shuzheng/zheng#109]
[演示地址]( http://upms.zhangshuzheng.cn/)
进去直接是tomcat admin 页面

**Comment by Doodlister** [comment]
你是不是配置了 hosts 文件了。

**Comment by weichengpei** [comment]
并没有修改过hosts文件，且也没有权限修改哦。
http://upms.zhangshuzheng.cn/ 不是你们的演示地址吗。

**Comment by zhoushijin** [comment]
http://47.93.195.63/zheng-upms-server/sso/login,这是演示地址，本地运行要改hosts

**Comment by haobinyuan** [comment]
@weichengpei  不是hosts的问题，upms.zhangshuzheng.cn会解析到作者的服务器ip上，作者部署的tomcat默认监听80端口，因此演示地址都不需要域名或ip后面拼个端口，多方便，你的演示地址http://upms.zhangshuzheng.cn只是进入tomcat首页了
