### ISSUE TITLE
我看了QQ群里的视频,字小的可怕,我用笔记本看的很辛苦

### ISSUE THREAD

**Issue by ithjz** [shuzheng/zheng#113]
我看了QQ群里的视频,字小的可怕,我用笔记本看的很辛苦

而且也不放到优酷上,差评,没有声音,
不知道为啥这么多关注,,,,

项目对于新手和私活项目来说,部署启动都比较麻烦,请问有良好的解决方法吗

**Comment by surick** [comment]
根据readme把该装的都装了，配置好，war包放到tomcat的webapps文件夹下面就好啦
