### ISSUE TITLE
这12k的star里面的水分不知道有几成

### ISSUE THREAD

**Issue by EachannWang** [shuzheng/zheng#155]

**Comment by shuzheng** [comment]
你让我这么解释？我没必要自欺欺人。

**Comment by shuzheng** [comment]
我一不图名、二不商用，我只是写套代码还招黑。影响到你了吗？

**Comment by jiaxiaofeicode** [comment]
人家只是说你这代码水平,不该有12k的star,我也看过你得代码,12K死人?你试试自己挂的demo都跑不通,撤了吧




------------------ 原始邮件 ------------------
发件人: "shuzheng"<notifications@github.com>;
发送时间: 2018年12月29日(星期六) 上午10:01
收件人: "shuzheng/zheng"<zheng@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [shuzheng/zheng] 这12k的star里面的水分不知道有几成 (#155)




我一不图名、二不商用，我只是写套代码还招黑。影响到你了吗？

**Comment by shuzheng** [comment]
本人不才，您可以取消star

**Comment by jiaxiaofeicode** [comment]
我去呀,怎么还给我发,我已经取消star了.既然是精华,自己留着慢慢汲取吧









------------------ 原始邮件 ------------------
发件人: "techThink"<notifications@github.com>;
发送时间: 2018年12月29日(星期六) 上午10:26
收件人: "shuzheng/zheng"<zheng@noreply.github.com>;
抄送: "贾小飞"<jiaxiaofei@vip.qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [shuzheng/zheng] 这12k的star里面的水分不知道有几成 (#155)




说句公道话：学习要切忌心浮气躁，遇到问题慢慢解决，该项目的启动视频，文档都齐全，慢慢来。这个项目12k，不是刷的，价值摆在这里。项目确实有小瑕疵，学习里面的精华就可以了。别人开源不易，付出的精力比你学习多的多！
