### ISSUE TITLE
求新群，都满了。

### ISSUE THREAD

**Issue by qiankeqin** [shuzheng/zheng#161]

**Comment by penghongru** [comment]
同上

**Comment by wangkun19930608** [comment]
有幸找到一个没满的，然后自己有一个小群，272383825，自己建立的，没有大佬，都是一块学习的，只是 把zheng群里面的文件转过去了，需要下载的可以加一下。文件只是来自大佬的群三305155242
[![0Y`1FQTH{%Z(B31NU~85~1E.png](https://i.loli.net/2019/05/05/5cce6bef0261f.png)](https://i.loli.net/2019/05/05/5cce6bef0261f.png)

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
