### ISSUE TITLE
项目部署到服务器问题

### ISSUE THREAD

**Issue by MrJackC** [shuzheng/zheng#163]
将项目部署到服务器，怎么样才能通过IP访问，在访问时怎么才能不跳转到域名。
因为不通过ip访问，局域网内的其他人访问，还需要在电脑上映射域名，有点麻烦，求指教！ 谢谢

**Comment by edenxu** [comment]
修改你的dev.properties下的server.url为指定ip加端口，然后同时修改upms_system表里对应的域名为相应的ip和端口即可
