### ISSUE TITLE
图用什么工具画的

### ISSUE THREAD

**Issue by 422053362** [shuzheng/zheng#29]
想问问，这样的图，用什么工具画的
https://github.com/shuzheng/zheng/raw/master/project-bootstrap/distributedSystem.png

**Comment by dongjinl** [comment]
我刚刚看了一下，用《亿图图示》似乎可以画这种3D的

**Comment by matrixxun** [comment]
同问

**Comment by FataliBud** [comment]
VISO可以画的。

**Comment by Jacob201311** [comment]
问一下进度图用什么软件
