### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by wuxingdefeng** [shuzheng/zheng#47]
问一下，我在zheng项目点击install之后，控制台显示
[INFO] zheng-demo-rpc-api ................................ SKIPPED
[INFO] zheng-demo-rpc-service ............................ SKIPPED
[INFO] zheng-demo-web Maven Webapp ....................... SKIPPED
都是这样的，怎么回事

**Comment by carker** [comment]
你安装一个插件maven helper，利用这个插件进行run
