### ISSUE TITLE
请问一下，是不是拦截到已认证的token就可以任意访问单点登录的子系统呢

### ISSUE THREAD

**Issue by a466350665** [shuzheng/zheng#5]
像这样，子系统URL+“？token=” + token
![image](https://cloud.githubusercontent.com/assets/19278040/23201321/0fdda798-f914-11e6-9c23-cd7d2a245dfa.png)

**Comment by shuzheng** [comment]
是的，目前正在改进：
1、认证成功，带回生成和子系统sessionId绑定的code，有效期5分钟；
2、子系统使用code+系统id+secret换取token；
3、子系统验证token。

**Comment by shuzheng** [comment]
回跳地址backurl也要做安全校验

**Comment by a466350665** [comment]
好的  期待

**Comment by xiaoguobiao** [comment]
这个应该就是一个变量名吧
