### ISSUE TITLE
zheng-upms-rpc-service下得jdbc.properties中值是加载得哪个环境？

### ISSUE THREAD

**Issue by 401825317** [shuzheng/zheng#50]
![image](https://user-images.githubusercontent.com/19526136/27258556-cf2fde1a-542f-11e7-81a5-e63cfbb1efe2.png)
这3个环境都值都改了，还是加载得127.0.0.1:3306，郁闷了

**Comment by shuzheng** [comment]
mvn package -P [dev|test|prod]
可指定引用哪个profile编译jdbc.properties文件
