### ISSUE TITLE
在线工具有没有那种pl/sql里面已经美化的语句,转成java ,stringbuild.append()那种的啊

### ISSUE THREAD

**Issue by tangchao0106** [shuzheng/zheng#66]
大神  在线工具有没有那种pl/sql里面已经美化的语句,转成java ,stringbuild.append()那种的啊,有没有啊地址发我419704299@qq.com

**Comment by shuzheng** [comment]
自己写一个吧，为自己定制：）

**Comment by shuzheng** [comment]
自己写一个吧，为自己定制：）
