### ISSUE TITLE
一些缺陷

### ISSUE THREAD

**Issue by hdatsf** [shuzheng/zheng#75]
1：没有集成swagger2，仅仅只是加了jar包
2：jar包管理有点乱，应该每个项目需要什么用什么，不能一股脑儿全丢common，其余项目全引用。

还在精读代码中，谢谢分享。

**Comment by shuzheng** [comment]
1、有swagger2的，也有ui页面
2、这个问题决定了使用的复杂度，在灵活和方便之前自己做权衡
