### ISSUE TITLE
修改配置

### ISSUE THREAD

**Issue by ihaodi** [shuzheng/zheng#81]
* 修改各dao模块和rpc-service模块的redis.properties、jdbc.properties、generator.properties数据库连接等配置信息，其中master.redis.password、master.jdbc.password、slave.jdbc.password、generator.jdbc.password密码值使用了AES加密，请使用com.zheng.common.util.AESUtil工具类修改这些值

这些默认值怎么修改

**Comment by greydesolate** [comment]
请先找到这个zheng-common\src\main\java\com\zheng\common\util\AESUtil.java
这里面是提供将字符串（各种密码明文）加密的方法。
全局在*.properties文件中查找master.redis.password、master.jdbc.password、slave.jdbc.password、generator.jdbc.password，将自己的明文密码用AESUtil加密后替换后面的value值。
