### ISSUE TITLE
用户分配角色，角色分配权限操作有吗？

### ISSUE THREAD

**Issue by lihua123569** [shuzheng/zheng#95]
用户分配角色，角色分配权限操作有吗？
新增权限--》新增角色--》新增用户
给用户分配角色，给角色分配权限操作哪里有体现？

**Comment by yuyixing** [comment]
在权限管理系统里面
![image](https://user-images.githubusercontent.com/13652629/32883488-82cdb4f4-caf2-11e7-8dc0-4c072021bfb6.png)

**Comment by lihua123569** [comment]
项目本地跑起来，看到了，谢谢
